version: '3'
services:
  app:
    container_name: docker-samba-timemachine
    image: mariomare22/docker-samba-timemachine
    restart: always
    network_mode: host
    environment:
      TM_USER: tm_user
      TM_PW: timemachine
      TM_SIZE: 512000
    volumes:
      - '/mnt/backup/docker/config/samba:/etc/samba'
      - '/mnt/backup/timemachine:/timemachine'
      - '/mnt/backup/foto:/foto'
      - '/mnt/nas/:/nas'
      - '/home/mario/docker/transmission/watch:/watch'
      - '/etc/localtime:/etc/localtime:ro'
