version: '3'
services:
  app:
    image: mariomare22/docker-samba-timemachine
    restart: always
    network_mode: host
    environment:
      TM_USER: tm_user
      TM_PW: timemachine
      TM_SIZE: 512000
    volumes:
      - '/mnt/nas/timemachine:/timemachine'
      - '/mnt/archive/Foto_backup:/foto'
      - '/mnt/nas/:/nas'
      - '/etc/localtime:/etc/localtime:ro'
